const sorts = [
    {
        name: "Bubble Sort",
        timeComplexity: 4,
        memory: 0,
        HTML: "<p>Bubble Sort</p><p>n<span class='power'>2</span></p><p>1</p>",
        selected: true,
        function: "bubbleSort",
    },
    {
        name: "Insertion Sort",
        timeComplexity: 4,
        memory: 0,
        HTML: "<p>Insertion Sort</p><p>n<span class='power'>2</span></p><p>1</p>",
        selected: false,
        function: "insertionSort",
    },
    {
        name: "Merge Sort",
        timeComplexity: 0,
        memory: 2,
        HTML: "<p>Merge Sort</p><p>n * log n</p><p>n</p>",
        selected: false,
        function: "mergeSort",
    },
    {
        name: "Heapsort",
        timeComplexity: 0,
        memory: 0,
        HTML: "<p>Heapsort</p><p>n * log n</p><p>1</p>",
        selected: false,
        function: "heapsort",
    },
    {
        name: "Quicksort",
        timeComplexity: 0,
        memory: 1,
        HTML: "<p>Quicksort</p><p>n * log n</p><p>log n</p>",
        selected: false,
        function: "quicksort",
    },
    {
        name: "Shellsort",
        timeComplexity: 3,
        memory: 0,
        HTML: "<p>Shellsort</p><p>n<span class='power'>4/3</span></p><p>1</p>",
        selected: false,
        function: "shellsort",
    },
    {
        name: "Comb Sort",
        timeComplexity: 4,
        memory: 0,
        HTML: " <p>Comb Sort</p><p>n<span class='power'>2</span></p><p>1</p>",
        selected: false,
        function: "combSort",
    },
    {
        name: "Cocktail Shaker Sort",
        timeComplexity: 4,
        memory: 0,
        HTML: "<p>Cocktail Shaker Sort</p><p>n<span class='power'>2</span></p><p>1</p>",
        selected: false,
        function: "cocktailShakerSort",
    },
    {
        name: "Gnome Sort",
        timeComplexity: 4,
        memory: 0,
        HTML: " <p>Gnome Sort</p><p>n<span class='power'>2</span></p><p>1</p>",
        selected: false,
        function: "gnomeSort",
    },
    {
        name: "Selection Sort",
        timeComplexity: 4,
        memory: 0,
        HTML: "<p>Selection Sort</p><p>n<span class='power'>2</span></p><p>1</p>",
        selected: false,
        function: "selectionSort",
    },
    {
        name: "Counting Sort",
        timeComplexity: 1,
        memory: 4,
        HTML: "<p>Counting Sort</p><p>n + r</p><p>n + r</p>",
        selected: false,
        function: "countingSort",
    },
    {
        name: "Radix Sort (LSD)",
        timeComplexity: 2,
        memory: 3,
        HTML: "<p>Radix Sort (LSD)</p><p>n * k/d</p><p>n + 2<span class='power'>d</span></p>",
        selected: false,
        function: "radixSort",
    },
    {
        name: "Bucket Sort",
        timeComplexity: 1,
        memory: 4,
        HTML: "<p>Bucket Sort</p><p>n + r</p><p>n + r</p>",
        selected: false,
        function: "bucketSort",
    }
];
